Default: &defaults
  database: Hello.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Hello_test.sqlite3
  <<: *defaults

Staging:
  database: Hello_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Hello_production.sqlite3
  poolsize: 100
  <<: *defaults
